# Use official Python image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

ARG VITE_ORCID_CLIENT_ID
ARG VITE_ORCID_CLIENT_SECRET
ARG VITE_ORCID_REDIRECT_URI

# Set workdir
WORKDIR /app

# Install dependencies
COPY backend/requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy project
COPY ./backend .

RUN echo "VITE_ORCID_CLIENT_ID=$VITE_ORCID_CLIENT_ID" >> .env
RUN echo "VITE_ORCID_CLIENT_SECRET=$VITE_ORCID_CLIENT_SECRET" >> .env
RUN echo "VITE_ORCID_REDIRECT_URI=$VITE_ORCID_REDIRECT_URI" >> .env

# Run FastAPI with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]