/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The Dashboard Data object is a JSON-LD representation of the data used in the dashboard. It contains information about the dashboard, including its ID, type, and various properties related to the dashboard's content.
 */
export interface DashboardData {
  /**
   * The unique identifier of the Dashboard Data object
   */
  "@id": string;
  /**
   * The type of the object, in this case DashboardData
   */
  "@type"?: "DashboardData";
  /**
   * The date on which the Taxonomic Expert was created or the item was added to a DataFeed, following the ISO Date Time Format yyyy-MM-dd'T'HH:mm:ss.SSSXXX
   */
  "schema:dateCreated"?: string;
  /**
   * The date on which the Expert was most recently modified or when the item's entry was modified within a DataFeed, following the ISO Date Time Format yyyy-MM-dd'T'HH:mm:ss.SSSXXX
   */
  "schema:dateModified"?: string;
  /**
   * Date of the expert was published, following the ISO Date Time Format yyyy-MM-dd'T'HH:mm:ss.SSSXXX
   */
  "schema:datePublished"?: string;
  /**
   * A unique identifier to identify the author; ORCID identifiers are valid
   */
  "schema:identifier"?: string;
  /**
   * The birth date of the Taxonomic Expert
   */
  "schema:birthDate"?: string;
  "schema:gender"?: string;
  [k: string]: unknown;
}
